In [1]:
import numpy as np

In [2]:
## create an empty array

arr=np.array([])
arr

array([], dtype=float64)

In [3]:
arr1=np.array([3,4,5,6])
arr1

array([3, 4, 5, 6])

In [4]:
# variable_name.attribute
# shape--> order of the matrix
arr1.shape

(4,)

In [5]:
# size-->number of elements
arr1.size

4

In [6]:
# ndim-->dimenional of data
arr1.ndim

1

In [7]:
#dtype--> datatype in the array elements
arr1.dtype

dtype('int64')

In [8]:
arr2=np.array([[4,3,1],[7,8,6],[9,1,4]])
arr2

array([[4, 3, 1],
       [7, 8, 6],
       [9, 1, 4]])

In [9]:
arr2.shape,arr2.size,arr2.ndim,arr2.dtype

((3, 3), 9, 2, dtype('int64'))

In [14]:
arr3=np.array([ [[4,5,8],[6,7,9]], [[9,3,5],[4,2,10]] ])
arr3

array([[[ 4,  5,  8],
        [ 6,  7,  9]],

       [[ 9,  3,  5],
        [ 4,  2, 10]]])

In [15]:
arr3.ndim

3

In [16]:
arr3.shape

(2, 2, 3)

In [17]:
arr3.dtype,arr3.size

(dtype('int64'), 12)

In [18]:
list_var=[3,5,6]
a1=np.array(list_var)

In [19]:
a1

array([3, 5, 6])

# reshape an array

In [58]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
arr4.shape

(12,)

In [62]:
result=arr4.reshape((4,3))

In [63]:
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
result.ndim

2

In [35]:
a2=result.reshape(-1) # returns 1d data
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## arange function

In [57]:
ar=np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
ar1=np.arange(1,101)
ar1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [41]:
ar2=np.arange(0,30,3)
ar2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [64]:
arr5=np.arange(1,13).reshape((2,2,3))
arr5

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [2]:
import numpy as np

In [3]:
ans=np.arange(1,13).reshape((2,2,3))
ans


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## one

In [5]:
one_mat=np.ones((3,3))
one_mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Broadcasting of an array

In [6]:
output=one_mat*3-one_mat*0.5
output

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [7]:
two_mat=np.ones((3,3))*2
two_mat

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [8]:
three_mat= two_mat+1
three_mat


array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [68]:
two_mat/two_mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
two_mat+two_mat

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [70]:
two_mat*two_mat

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [71]:
two_mat**3

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

## To find max,min, index value of max and min value

In [11]:
arr6=np.random.randint(1,100,10)
arr6

array([72, 64, 93, 79, 91, 32, 68, 24, 34, 93], dtype=int32)

In [12]:
arr6.max()

np.int32(93)

In [13]:
arr6.min()

np.int32(24)

In [14]:
arr6.argmax() # returns the index value of max/highest number

np.int64(2)

In [15]:
arr6.argmin() # returns the index value of mini/lowest number

np.int64(7)

In [18]:
np.random.randint(1,10,3)

array([2, 1, 4], dtype=int32)

In [29]:
np.random.randint(55,size=(3,2))

array([[ 4, 37],
       [ 1, 34],
       [35, 36]], dtype=int32)

## generation of random numbers

# rand function-- returns random number from 0 to 1

In [21]:
arr7=np.random.rand(5) # generate five random numbers from 0 to 1
arr7

array([0.26586232, 0.31658702, 0.90429865, 0.50914077, 0.2982589 ])

In [23]:
arr8=np.random.rand() # generate a random number from 0 to 1
arr8

0.9777888092851468

In [24]:
arr9=np.random.rand(3,4) # create a 2d random numbers of a shape 3,4
arr9

array([[0.02310429, 0.62843402, 0.32511236, 0.15346256],
       [0.73874131, 0.53105193, 0.42247422, 0.37588297],
       [0.41537633, 0.91548421, 0.39745644, 0.51388043]])

# randn function-- returns random number from -3 to +3

In [30]:
np.random.randn() #Return a sample (or samples) from the "standard normal" distribution.

1.827457097319814

In [33]:
np.random.randn(15) # return 15 random numbers from -3 to +3

array([ 1.79870946, -0.56512096,  0.37630401,  0.53675068, -0.54834487,
        0.72170383, -0.21212342, -0.749666  ,  0.92917856, -0.90744239,
       -1.4798837 , -0.92816187,  0.96602734, -0.5996044 , -0.22792905])

In [34]:
np.random.randn(3,4) # retruns 2d data in the shape 3,4

array([[ 0.09286464,  0.93838714,  0.13029416,  0.45404285],
       [-0.50090624,  0.35264156,  0.32639712,  0.7870456 ],
       [-2.28543581,  2.51994861,  1.39559794,  1.73954504]])

In [35]:
np.random.randn(3,2,3)

array([[[ 0.80478272,  0.12513559, -0.6309541 ],
        [-1.03768633, -0.75188105,  0.49535473]],

       [[ 0.94032158,  0.11996944,  1.99586897],
        [ 0.46959967,  1.87365439, -0.20333263]],

       [[-0.95947066,  0.17792525, -0.39383868],
        [ 1.29145176, -0.95894629, -1.28800854]]])

## copy function

In [44]:
arr1 =np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [45]:
arr2=arr1 # assigning operator is not recommended to take back up
arr2

array([1, 2, 3, 4, 5])

In [46]:
arr2[2] # access an element 3 by using index value

np.int64(3)

In [47]:
arr2[2]=100  # assign new vLUE TO THE INDEX 2

In [48]:
arr2

array([  1,   2, 100,   4,   5])

In [49]:
arr1 # effected on arr1 as well

array([  1,   2, 100,   4,   5])

In [50]:
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [51]:
arr2=arr1.copy() # recommmended to take back up
arr2

array([10, 20, 30, 40, 50])

In [52]:
arr2[2]=10000

In [53]:
arr2

array([   10,    20, 10000,    40,    50])

In [55]:
arr1

array([10, 20, 30, 40, 50])

# linspace--(start,end,no of observation,retstep)

In [64]:
np.linspace(1,10,10,retstep=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), np.float64(1.0))

In [65]:
np.linspace(0,20,5,retstep=True)

(array([ 0.,  5., 10., 15., 20.]), np.float64(5.0))

In [68]:
np.linspace(1,10,6,retstep=True)

(array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ]), np.float64(1.8))

In [67]:
np.linspace(1,20) # by default it will genereate 50 obeservation

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

# ARRAY INDEXING

In [70]:
arr3=np.array([3,9,12,15,18,21,24,27])
arr3

array([ 3,  9, 12, 15, 18, 21, 24, 27])

In [71]:
arr3[5]

np.int64(21)

In [72]:
arr3[0:5]

array([ 3,  9, 12, 15, 18])

In [73]:
arr3[-2]

np.int64(24)

In [74]:
arr3[::2]

array([ 3, 12, 18, 24])

# array filtering

In [75]:
arr3

array([ 3,  9, 12, 15, 18, 21, 24, 27])

In [76]:
arr3>20

array([False, False, False, False, False,  True,  True,  True])

In [79]:
np.where(arr3>20) #    returns index values of true element

(array([5, 6, 7]),)

# Indexing on 2D

In [80]:
arr_2d = np.array([[1,2,3],[12,15,18],[64,96,128]])

#Show
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [81]:
arr_2d[:,:]

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [82]:
arr_2d[1:3,:]

array([[ 12,  15,  18],
       [ 64,  96, 128]])

In [83]:
arr_2d[:,1:3]

array([[  2,   3],
       [ 15,  18],
       [ 96, 128]])

In [84]:
arr_2d[1:3,1:3]

array([[ 15,  18],
       [ 96, 128]])

In [85]:
arr_2d[::2,:]

array([[  1,   2,   3],
       [ 64,  96, 128]])

In [86]:
arr_2d[:,::2]

array([[  1,   3],
       [ 12,  18],
       [ 64, 128]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [87]:
arr1=np.ones((10,10))
arr1.shape

(10, 10)

In [88]:
arr1.size

100

In [89]:
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [90]:
len(arr1)

10

In [93]:
for i in range(len(arr1)): # range(10)--0 to 9
  arr1[i]=i+10 # i value for the first iteration i=0 .a[0]--->first row=0
          

In [94]:
arr1

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [15., 15., 15., 15., 15., 15., 15., 15., 15., 15.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [17., 17., 17., 17., 17., 17., 17., 17., 17., 17.],
       [18., 18., 18., 18., 18., 18., 18., 18., 18., 18.],
       [19., 19., 19., 19., 19., 19., 19., 19., 19., 19.]])

In [95]:
arr1[:,0:3]>20

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [96]:
arr1[:,[1,4,6]]

array([[10., 10., 10.],
       [11., 11., 11.],
       [12., 12., 12.],
       [13., 13., 13.],
       [14., 14., 14.],
       [15., 15., 15.],
       [16., 16., 16.],
       [17., 17., 17.],
       [18., 18., 18.],
       [19., 19., 19.]])

In [97]:
arr1[[1,4,5],:]

array([[11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [15., 15., 15., 15., 15., 15., 15., 15., 15., 15.]])

# Happy Learning...!!